import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { MeshoptDecoder } from 'three/examples/jsm/libs/meshopt_decoder.module.js';
import { BODY_VARIANTS } from '../../src/anatomy/bodyVariants';
import { applyAnatomicPose } from '../../src/services/anatomicPose';
import { applyCustomPose, serializeCustomPose } from '../../src/services/poseRig';
import { captureJointAngleRestReference } from '../../src/services/jointAngles';
import { BODY_ASSESSMENT_MOTIONS } from '../../src/services/assessmentBodyMotions';
import { buildSequencePoses, resolveComposedMotion } from '../../src/services/motionSequence';
import { setRomClampEnabled } from '../../src/services/poseRomClamp';
import { createProneSkinSupport as originalFactory } from './captured-prone-measure-original';
import { createProneSkinSupport as candidateFactory } from './captured-prone-measure-candidate';

setRomClampEnabled(false);
const hash = (value: Uint8Array) => createHash('sha256').update(value).digest('hex');
const stats = (globalThis as any).__measureReuse = { calls: 0, hits: 0, fallback: 0, keyMs: 0 };
const report: any = { scope: 'Additional exact measurement cache mutation/ownership checks on all three real rigs. Standard geometry writes use Three needsUpdate; supplied callbacks and overridden vertex/attribute accessors always use the original uncached path. No clinical range or source runtime changes.', runs: [],
  copies: Object.fromEntries(['original', 'candidate'].map(name => [name, hash(readFileSync(new URL(`./captured-prone-measure-${name}.ts`, import.meta.url)))])) };
for (const variant of ['male', 'female', 'neutral'] as const) {
  const variantCfg = BODY_VARIANTS[variant], bytes = readFileSync(new URL(`../../models/painmap3D_${variant}.runtime.glb`, import.meta.url));
  const root = (await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parseAsync(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength), '')).scene;
  root.scale.setScalar(variantCfg.pose.rootScale); applyAnatomicPose(root, variantCfg); root.updateMatrixWorld(true);
  const skins: THREE.SkinnedMesh[] = []; root.traverse(node => { if ((node as THREE.SkinnedMesh).isSkinnedMesh) skins.push(node as THREE.SkinnedMesh); });
  const skinned = skins[0]!, baselinePose = serializeCustomPose(skinned.skeleton, variantCfg, variant), rest = captureJointAngleRestReference(skinned.skeleton, variantCfg);
  const sequence = buildSequencePoses(baselinePose, resolveComposedMotion(BODY_ASSESSMENT_MOTIONS['extension-clearing']!('R'), variantCfg), variantCfg, rest);
  applyCustomPose(skinned.skeleton, variantCfg, sequence.poses[1]!); root.quaternion.fromArray(sequence.roots[1]!.quat); root.updateMatrixWorld(true);
  const options = { root, skinned, variantCfg, baselinePose, rest };
  let helpers = [originalFactory(options), candidateFactory(options)];
  const snapshot = () => skinned.skeleton.bones.map(bone => [...bone.position.toArray(), ...bone.quaternion.toArray(), ...bone.scale.toArray(), ...bone.matrixWorld.toArray()]);
  const restore = (values: number[][]) => { skinned.skeleton.bones.forEach((bone, i) => { bone.position.fromArray(values[i]!); bone.quaternion.fromArray(values[i]!, 3); bone.scale.fromArray(values[i]!, 7); }); root.updateMatrixWorld(true); };
  const run: any = { variant, assetSha256: hash(bytes), cases: [] };
  const pair = (label: string, input: any = {}, fresh = true) => {
    const before = snapshot(), rootBefore = [...root.position.toArray(), ...root.quaternion.toArray(), ...root.scale.toArray()];
    const expected = helpers[0]!.solve(input), expectedPose = snapshot(); restore(before);
    const actual = helpers[1]!.solve(input); assert.deepEqual(actual, expected, `${variant} ${label} result`); assert.deepEqual(snapshot(), expectedPose, `${variant} ${label} poses/worlds`);
    assert.deepEqual([...root.position.toArray(), ...root.quaternion.toArray(), ...root.scale.toArray()], rootBefore, `${label} root ownership`);
    const measured = helpers[1]!.measure();
    if (fresh) assert.deepEqual(measured, candidateFactory(options).measure(), `${variant} ${label} fresh measurement`);
    const originalMinimum = measured.pelvis.minimumY; measured.pelvis.minimumY = 12345; measured.head.mesh = 'caller-mutated';
    assert.equal(helpers[1]!.measure().pelvis.minimumY, originalMinimum, `${label} result ownership`);
    run.cases.push({ label, exactResult: true, exactPoseAndWorld: true, exactFreshMeasurement: fresh, freshReturnedRecords: true });
  };
  pair('initial');
  root.position.set(.17, .034, -.28); root.updateMatrixWorld(true); pair('root translation');
  root.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), .17)); root.updateMatrixWorld(true); pair('root heading');
  pair('changed floor', { floorY: .043 });
  pair('changed patient', { constraints: { L_Leg: { kneeFlexion: { availableRange: { min: 0, max: 0 } } } } });
  skinned.position.z += .003; root.updateMatrixWorld(true); pair('mesh local');
  const morph = skinned.geometry.getAttribute('position').clone();
  for (let i = 0; i < morph.count; i++) morph.setXYZ(i, 0, .0007, 0);
  skinned.geometry.morphTargetsRelative = true; skinned.geometry.morphAttributes.position = [morph]; skinned.morphTargetInfluences = [.4]; pair('new morph');
  skinned.morphTargetInfluences[0] = .8; pair('morph influence');
  morph.setY(0, .002); morph.needsUpdate = true; pair('morph geometry');
  const originalBindMode = skinned.bindMode; skinned.bindMode = 'detached'; skinned.bindMatrixInverse.elements[13]! += .001; pair('detached inverse binding');
  skinned.bindMode = originalBindMode; root.updateMatrixWorld(true); pair('binding restored');
  const twist = skinned.skeleton.bones.find(bone => /L_ThighTwist/.test(bone.name))!; twist.quaternion.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), .012)); root.updateMatrixWorld(true); pair('helper pose');
  const vertexOriginal = skins.map(skin => skin.getVertexPosition); let extraY = .001;
  skins.forEach((skin, index) => { skin.getVertexPosition = function(vertex, target) {
    vertexOriginal[index]!.call(this, vertex, target);
    const inverse = this.matrixWorld.clone().invert(); return target.add(new THREE.Vector3(0, extraY, 0).applyMatrix4(inverse).sub(new THREE.Vector3().applyMatrix4(inverse)));
  }; });
  const beforeFallback = stats.fallback; pair('custom vertex closure', {}, false); extraY = .002; pair('custom vertex closure state', {}, false);
  assert.ok(stats.fallback > beforeFallback); skins.forEach((skin, index) => { skin.getVertexPosition = vertexOriginal[index]!; });
  pair('standard vertex restored');
  const position = skinned.geometry.getAttribute('position'), getY = position.getY; let localOffset = .0001;
  position.getY = function(index) { return getY.call(this, index) + localOffset; };
  const beforeAttributeFallback = stats.fallback; pair('custom attribute accessor', {}, false); localOffset = .0002; pair('custom attribute state', {}, false);
  assert.ok(stats.fallback > beforeAttributeFallback); position.getY = getY; pair('standard attribute restored');
  let shift = .001;
  const sampleSkin = <T>(read: () => T) => { const y = root.position.y; root.position.y += shift; root.updateMatrixWorld(true); try { return read(); } finally { root.position.y = y; root.updateMatrixWorld(true); } };
  helpers = [originalFactory({ ...options, sampleSkin }), candidateFactory({ ...options, sampleSkin })];
  const beforeCallbackFallback = stats.fallback; pair('custom sample callback', {}, false); shift = .002; pair('custom callback state', {}, false); assert.ok(stats.fallback > beforeCallbackFallback);
  report.runs.push(run); console.log(JSON.stringify({ variant, cases: run.cases.length }));
}
report.measurementReuse = stats;
writeFileSync(process.argv[2]!, JSON.stringify(report, null, 2) + '\n', { flag: 'wx' });
