/** Actual helper lifetime mutation reproduction. Production assets unchanged. */
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/examples/jsm/libs/meshopt_decoder.module.js';
import {BODY_VARIANTS} from '../../src/anatomy/bodyVariants';
import {applyAnatomicPose} from '../../src/services/anatomicPose';
import {applyCustomPose,serializeCustomPose} from '../../src/services/poseRig';
import {captureJointAngleRestReference} from '../../src/services/jointAngles';
import {resolveComposedMotion} from '../../src/services/motionSequence';
import {sampleComposedMotion} from '../../src/services/motionRecording';
import {BODY_ASSESSMENT_MOTIONS} from '../../src/services/assessmentBodyMotions';
import {createProneSkinSupport} from '../../src/services/proneSkinSupport';
import {setRomClampEnabled} from '../../src/services/poseRomClamp';
setRomClampEnabled(false);
const hash=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
const identity=()=>Object.fromEntries(['proneSkinSupport','motionRecording','motionRigInputKey','handContactPose','footContact'].map(n=>[n,hash(readFileSync(new URL(`../../src/services/${n}.ts`,import.meta.url)))]));
const before=identity(),cfg=BODY_VARIANTS.male,bytes=readFileSync(new URL('../../models/painmap3D_male.runtime.glb',import.meta.url));
const root=(await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;
root.scale.setScalar(cfg.pose.rootScale);applyAnatomicPose(root,cfg);root.updateMatrixWorld(true);let skinned!:THREE.SkinnedMesh;
root.traverse(n=>{if(!skinned&&(n as THREE.SkinnedMesh).isSkinnedMesh)skinned=n as THREE.SkinnedMesh;});
const baselinePose=serializeCustomPose(skinned.skeleton,cfg,'male'),rest=captureJointAngleRestReference(skinned.skeleton,cfg),rp=root.position.clone(),rq=root.quaternion.clone();
const frame=sampleComposedMotion(resolveComposedMotion(BODY_ASSESSMENT_MOTIONS['extension-clearing']!('R'),cfg),{baselinePose,rest,variantCfg:cfg,skeletonHarness:{root,skinned},sampleHz:60,frameTimesMs:[2500]}).frames[0]!;
const restore=()=>{applyCustomPose(skinned.skeleton,cfg,frame.pose);root.position.copy(rp).add(new THREE.Vector3().fromArray(frame.root.translateM));root.quaternion.copy(rq).multiply(new THREE.Quaternion().fromArray(frame.root.orientQuat));root.updateMatrixWorld(true);};
const options={root,skinned,variantCfg:cfg,baselinePose,rest};
restore();const warm=createProneSkinSupport(options),initial=warm.solve(),witness=initial.regions.pelvis;
const mesh=root.getObjectByName(witness.mesh) as THREE.SkinnedMesh,ids=mesh.geometry.getAttribute('skinIndex'),weights=mesh.geometry.getAttribute('skinWeight');
let slot=0;for(let i=1;i<weights.itemSize;i++)if(weights.getComponent(witness.vertex,i)>weights.getComponent(witness.vertex,slot))slot=i;
const oldIndex=ids.getComponent(witness.vertex,slot),newIndex=mesh.skeleton.bones.findIndex(b=>/Waist$/.test(b.name));if(newIndex<0)throw Error('Missing lower spine');
ids.setComponent(witness.vertex,slot,newIndex);ids.needsUpdate=true;
restore();const warmMeasure=warm.measure(),fresh=createProneSkinSupport(options),freshMeasure=fresh.measure();
restore();const warmResult=warm.solve();const warmPose=serializeCustomPose(skinned.skeleton,cfg,'male');
restore();const freshResult=fresh.solve();const freshPose=serializeCustomPose(skinned.skeleton,cfg,'male');
const after=identity();const report={scope:'Retained helper versus rebuilt helper after a single in-memory dominant skin-index reassignment at peak. The actual live helper persists for one playComposed; no current host UI changing skin weights mid-play was found. No production asset edit.',before,after,sourceStable:JSON.stringify(before)===JSON.stringify(after),assetSha256:hash(bytes),edit:{mesh:mesh.name,vertex:witness.vertex,slot,weight:weights.getComponent(witness.vertex,slot),oldBone:mesh.skeleton.bones[oldIndex]!.name,newBone:mesh.skeleton.bones[newIndex]!.name,skinIndexVersion:ids.version},initial,warmMeasure,freshMeasure,warmResult,freshResult,warmPose,freshPose};
writeFileSync(process.argv[2]!,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({sourceStable:report.sourceStable,edit:report.edit,warmPelvis:warmMeasure.pelvis,freshPelvis:freshMeasure.pelvis,warmResult:{feasible:warmResult.feasible,reused:warmResult.reusedSolution},freshResult:{feasible:freshResult.feasible,reused:freshResult.reusedSolution},exactPoseEqual:JSON.stringify(warmPose)===JSON.stringify(freshPose)},null,2));
