// Generated by scripts/build-shoulder-v2-models.mjs.
export const SHOULDER_RIG_ASSET_HASHES = {"male":"3851d2b9e279dcbc5e6cba49926f987e60c69c141d62396a1c2848d291f2fd7c","female":"0b7dc2a09396219ee1e8584f160aa87eee77f5e5ffb30d88e8ea0f1bba18ff76","neutral":"8d9122bad38e5e266d9ed0303a8c98a06feb80e8e1f9e57d6316c3fd70718561"} as const;
